# Generated by Django 5.2.7 on 2025-10-16 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='频道的唯一名称，至少2个字符', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='频道名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '频道',
                'verbose_name_plural': '频道',
                'ordering': ['-created_at'],
            },
        ),
    ]
