# Generated by Django 5.2.7 on 2025-10-16 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Channels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='频道成员列表', to=settings.AUTH_USER_MODEL, verbose_name='成员'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['name'], name='Channels_ch_name_67eeaf_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['created_at'], name='Channels_ch_created_a299af_idx'),
        ),
    ]
