# Generated by Django 5.2.7 on 2025-10-16 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Messenger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='发送者'),
        ),
        migrations.AddField(
            model_name='plain',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plain', to='Messenger.post', verbose_name='关联帖子'),
        ),
        migrations.AddField(
            model_name='vote',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='Messenger.post', verbose_name='关联帖子'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['channel', 'created_at'], name='Messenger_p_channel_096050_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['sender', 'created_at'], name='Messenger_p_sender__1c59b4_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type'], name='Messenger_p_post_ty_4d4cc0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('channel', 'in_channel_id')},
        ),
    ]
