name: CI

on:
  push:
  pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: test-secret-key
      SUPER_OPERATORS: user@example.com
      PYTHONUNBUFFERED: "1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run database migrations
        run: |
          python manage.py migrate --noinput

      - name: Run integration flow
        run: |
          ./scripts/run_integration_flow.sh
